version: '3.7'
services:
  client:
    container_name: finding-falcon-frontend
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true 