const actionTypes = {
    FETCH_PLANETS_IS_LOADING: 'FETCH_PLANETS_IS_LOADING',
    FETCH_PLANETS_SUCCESS: 'FETCH_PLANETS_SUCCESS',
    FETCH_PLANETS_FAILURE: 'FETCH_PLANETS_SUCCESS',

    FETCH_VEHICLES_IS_LOADING: 'FETCH_VEHICLES_IS_LOADING',
    FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
    FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_SUCCESS',
    
    FETCH_TOKEN_IS_LOADING: 'FETCH_TOKEN_IS_LOADING',
    FETCH_TOKEN_SUCCESS: 'FETCH_TOKEN_SUCCESS',
    FETCH_TOKEN_FAILURE: 'FETCH_TOKEN_FAILURE',

    FETCH_RESULT_IS_LOADING: 'FETCH_RESULT_IS_LOADING',
    FETCH_RESULT_SUCCESS: 'FETCH_RESULT_SUCCESS',
    FETCH_LAST_SAVED_RESULT_SUCCESS: 'FETCH_LAST_SAVED_RESULT_SUCCESS',
    FETCH_RESULT_FAILURE: 'FETCH_RESULT_FAILURE',
}

export default actionTypes;